### PR TITLE
Delete vendor directory

### PR DESCRIPTION
**Pull request by jngo2**
Removing the vendor directory as requested.

### CODE REVIEW

**Comment by micahhausler** [comment]
@jngo2 I think you'll have to fix some of the test expectations about vendored code

**Comment by xdu31** [comment]
@jngo2 Need to change on lint target in makefile top resolve `pull-aws-encryption-provider-verify`: https://github.com/kubernetes-sigs/aws-encryption-provider/blob/master/Makefile#L10-L11 as part of the prow job definition in [https://github.com/kubernetes/test-infra/blob/f7e21a3c18f4f4bbc7ee170675ed53e4544a[…]ig/jobs/kubernetes-sigs/aws-encryption-provider/presubmits.yaml](https://github.com/kubernetes/test-infra/blob/f7e21a3c18f4f4bbc7ee170675ed53e4544a0632/config/jobs/kubernetes-sigs/aws-encryption-provider/presubmits.yaml#L12)

**Pull request merged**
