### PR TITLE
update owners file

### LINKED ISSUE #7: Your OWNERS file is incorrect
https://github.com/kubernetes-sigs/aws-encryption-provider/blob/master/OWNERS

Please update this file with the list of people who are actually OWNERS for this repo, and remove the steering committee

### PR DESCRIPTION
**Pull request by sethpollack**
fixes #7

### CODE REVIEW

**Comment by spiffxp** [comment]
... this repo is missing some automation

**Comment by spiffxp** [comment]
... right, tide isn't turned on for this repo either

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/pull/8944

**Comment by sethpollack** [comment]
Thanks!

**Comment by spiffxp** [comment]
In theory, once that merges and deploys, tide will merge this.  Let's find out.

**Comment by spiffxp** [comment]
woohoo!

**Pull request merged**
