### PR TITLE
enable gomodules to fix docker image creation

### PR DESCRIPTION
**Pull request by rajatjindal**
add ```ENV GO111MODULE=on``` to Dockerfile to be able to create docker image.

### CODE REVIEW

**Comment by rajatjindal** [comment]
thanks for merging the PR @sethpollack . 

can I use this PR to ask a question too: at this stage, do you think aws-encryption-provider can be used in Production? 

(I understand no guarantee, but just recommendation)

Thanks
Rajat Jindal

**Comment by sethpollack** [comment]
Not sure, I personally would wait until we have e2e tests.

**Pull request merged**
