### PR TITLE
Dockerfile: build from "busybox" to include "/bin/sh"

### PR DESCRIPTION
**Pull request by gyuho**
Useful for log forwarding

### CODE REVIEW

**Comment by gyuho** [comment]
/assign @micahhausler

Tested and confirmed that it works

```yaml
    command:
    - /bin/sh
    - -c
    - /aws-encryption-provider
      ...
      1>>DIR/aws-encryption-provider.log 2>&1
```

**Comment by leakingtapan** [comment]
I think 1.15 K8s is going with distroless which doesn't use `sh` (so this is a problem we need to solve anyway). Is there a better way to handle log forwarding with scratch image?

**Comment by micahhausler** [comment]
> I think 1.15 K8s is going with distroless which doesn't use `sh` (so this is a problem we need to solve anyway). Is there a better way to handle log forwarding with scratch image?

The way to do this would be to consume the runtime's logfile. Both containerd and docker write this to a file, so it should be fairly trivial to tail that instead of a named file

**Comment by micahhausler** [comment]
/hold

waiting on a rebase

**Pull request merged**
