### PR TITLE
replace glog with zap

### PR DESCRIPTION
**Pull request by rajatjindal**
This is just replacement of glog with zap. In upcoming PR, I plan to push following changes:

- allow user to override level
- add/improve logging where needed

### CODE REVIEW

**Comment by rajatjindal** [comment]
a sample output of logs with zap:

```
$ go run cmd/server/main.go -listen ./socket.sock
{"level":"info","timestamp":"2020-01-16T16:14:45.816+0530","caller":"server/main.go:95","message":"Healthchecks server started","port":":8080"}
{"level":"info","timestamp":"2020-01-16T16:14:45.816+0530","caller":"server/main.go:96","message":"Plugin server started","port":"./socket.sock"}
^C{"level":"info","timestamp":"2020-01-16T16:14:47.237+0530","caller":"server/main.go:103","message":"Received signal","signal":"interrupt"}
{"level":"info","timestamp":"2020-01-16T16:14:47.237+0530","caller":"server/main.go:104","message":"Closing client connection"}
{"level":"info","timestamp":"2020-01-16T16:14:47.237+0530","caller":"server/main.go:106","message":"Shutting down server"}
{"level":"info","timestamp":"2020-01-16T16:14:47.238+0530","caller":"server/main.go:108","message":"Exiting..."}
```

**Comment by rajatjindal** [comment]
we are running into: https://github.com/golang/go/issues/28102 I am trying to update verify-vendor.sh to take this into consideration.

**Comment by rajatjindal** [comment]
I think (and hope) this should fix it: https://github.com/kubernetes/test-infra/pull/15942

**Comment by micahhausler** [comment]
@rajatjindal Looks like kubernetes/test-infra#15942 broke the builds because `make` isn't included in the alpine image

**Comment by micahhausler** [comment]
Test was fixed in kubernetes/test-infra#15947

/retest

**Pull request merged**
